/**
 * v1.2 — Director Route 2.0 persistence tests.
 *
 * Uses `fake-indexeddb` (already in the project's devDeps) so
 * the IDB code path runs under happy-dom. The persistence
 * layer is pure idb-keyval (no Tauri), so `fake-indexeddb`'s
 * in-memory store is exactly the production codepath.
 *
 * No test-time clock injection needed: the run id is
 * generated by the loop, not by persistence. We pre-write
 * the runs with deterministic ids and verify the round trip.
 */
import { describe, it, expect, beforeEach } from 'vitest';
import 'fake-indexeddb/auto';
import {
  saveRun,
  loadRun,
  updateRun,
  listRunsForUser,
  deleteRun,
  runKey,
  userIndexKey,
  type AgentRun,
} from '@/lib/agent-loop/persistence';
import type { Step } from '@/lib/agent-loop/log';

function makeStep(over: Partial<Step> = {}): Step {
  return {
    idx: 0,
    type: 'plan',
    cost: 0,
    timestamp: 1,
    ...over,
  };
}

function makeRun(over: Partial<AgentRun> = {}): AgentRun {
  return {
    runId: 'run_test_001',
    userId: 'user_1',
    startedAt: 1000,
    finishedAt: 2000,
    niches: ['Marvel'],
    genres: ['Noir'],
    ideaConcept: 'Darth Vader in Iron Man suit',
    steps: [makeStep({ idx: 0, type: 'plan' }), makeStep({ idx: 1, type: 'final', cost: 0.01 })],
    totalCost: 0.01,
    finalPrompt: 'A noir Iron Vader under neon rain…',
    truncatedBy: 'natural',
    modelId: 'MiniMax-M3',
    ...over,
  };
}

beforeEach(async () => {
  // Wipe the in-memory IDB between tests so the user-index
  // doesn't bleed across cases.
  const { clear } = await import('idb-keyval');
  await clear();
});

describe('runKey / userIndexKey', () => {
  it('prefixes run ids with "agent_run:"', () => {
    expect(runKey('abc')).toBe('agent_run:abc');
  });
  it('prefixes user ids with "agent_runs_index:"', () => {
    expect(userIndexKey('u1')).toBe('agent_runs_index:u1');
  });
});

describe('saveRun + loadRun (round-trip)', () => {
  it('returns the same run that was written', async () => {
    const run = makeRun();
    await saveRun(run);
    const loaded = await loadRun(run.runId);
    expect(loaded).toEqual(run);
  });

  it('returns null when the run does not exist', async () => {
    expect(await loadRun('does-not-exist')).toBe(null);
  });

  it('preserves every step in the log', async () => {
    const run = makeRun({
      steps: [
        makeStep({ idx: 0, type: 'plan', reasoning: 'plan text' }),
        makeStep({ idx: 1, type: 'tool_call', tool: 'trending_search', cost: 0.005 }),
        makeStep({ idx: 2, type: 'tool_result', tool: 'trending_search' }),
        makeStep({ idx: 3, type: 'final', cost: 0.02 }),
      ],
      totalCost: 0.025,
    });
    await saveRun(run);
    const loaded = await loadRun(run.runId);
    expect(loaded?.steps).toHaveLength(4);
    expect(loaded?.totalCost).toBe(0.025);
  });

  it('tolerates a missing finalPrompt (error runs)', async () => {
    const run = makeRun({ finalPrompt: undefined });
    await saveRun(run);
    const loaded = await loadRun(run.runId);
    expect(loaded?.finalPrompt).toBeUndefined();
  });
});

describe('saveRun — user index', () => {
  it('adds a new run to the user index', async () => {
    await saveRun(makeRun({ runId: 'r1', userId: 'u1' }));
    const runs = await listRunsForUser('u1');
    expect(runs).toHaveLength(1);
    expect(runs[0]?.runId).toBe('r1');
  });

  it('is idempotent — re-saving the same run does not duplicate the index entry', async () => {
    await saveRun(makeRun({ runId: 'r1', userId: 'u1' }));
    await saveRun(makeRun({ runId: 'r1', userId: 'u1' }));
    await saveRun(makeRun({ runId: 'r1', userId: 'u1' }));
    const runs = await listRunsForUser('u1');
    expect(runs).toHaveLength(1);
  });

  it('keeps separate indexes per user', async () => {
    await saveRun(makeRun({ runId: 'r1', userId: 'u1' }));
    await saveRun(makeRun({ runId: 'r2', userId: 'u2' }));
    expect((await listRunsForUser('u1')).map((r) => r.runId)).toEqual(['r1']);
    expect((await listRunsForUser('u2')).map((r) => r.runId)).toEqual(['r2']);
  });
});

describe('listRunsForUser', () => {
  it('returns newest-first', async () => {
    await saveRun(makeRun({ runId: 'r1', userId: 'u1', startedAt: 100 }));
    await saveRun(makeRun({ runId: 'r2', userId: 'u1', startedAt: 200 }));
    await saveRun(makeRun({ runId: 'r3', userId: 'u1', startedAt: 300 }));
    const runs = await listRunsForUser('u1');
    expect(runs.map((r) => r.runId)).toEqual(['r3', 'r2', 'r1']);
  });

  it('respects the limit option', async () => {
    await saveRun(makeRun({ runId: 'r1', userId: 'u1', startedAt: 100 }));
    await saveRun(makeRun({ runId: 'r2', userId: 'u1', startedAt: 200 }));
    await saveRun(makeRun({ runId: 'r3', userId: 'u1', startedAt: 300 }));
    const runs = await listRunsForUser('u1', { limit: 2 });
    expect(runs).toHaveLength(2);
    expect(runs.map((r) => r.runId)).toEqual(['r3', 'r2']);
  });

  it('returns [] for an unknown user', async () => {
    expect(await listRunsForUser('nobody')).toEqual([]);
  });
});

describe('updateRun', () => {
  it('overwrites the existing record', async () => {
    await saveRun(makeRun({ runId: 'r1', finalPrompt: 'old prompt' }));
    await updateRun(makeRun({ runId: 'r1', finalPrompt: 'new prompt' }));
    const loaded = await loadRun('r1');
    expect(loaded?.finalPrompt).toBe('new prompt');
  });

  it('adds the id to the user index if not present', async () => {
    // Simulate the edge case where the original saveRun
    // failed mid-write but updateRun is retried.
    await updateRun(makeRun({ runId: 'r1', userId: 'u1' }));
    const runs = await listRunsForUser('u1');
    expect(runs.map((r) => r.runId)).toEqual(['r1']);
  });
});

describe('deleteRun', () => {
  it('removes the run and its index entry', async () => {
    await saveRun(makeRun({ runId: 'r1', userId: 'u1' }));
    const removed = await deleteRun('r1', 'u1');
    expect(removed).toBe(true);
    expect(await loadRun('r1')).toBe(null);
    expect(await listRunsForUser('u1')).toEqual([]);
  });

  it('returns false when the run is not in the index', async () => {
    const removed = await deleteRun('does-not-exist', 'u1');
    expect(removed).toBe(false);
  });
});
